name: Automatic Testing for Task Management Web App

on:
  push:
    branches:
      - main # Workflow will be triggered whenever there is a push in main branch
jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code from GitHub Repo
      uses: actions/checkout@v3
    
    - name: Setup Node.js in Ubuntu
      uses: actions/setup-node@v3
      with:
        node-version: 18
    
    - name: Remove existing node_modules folder from cloned project
      run: rm -rf /home/runner/work/Task_Manager_DevOPS_P05_Kiirthanah/Task_Manager_DevOPS_P05_Kiirthanah/node_modules/*
    
    - name: Install dependencies for based on package.json
      run: npm install
      
    - name: Run tests in "tests" folder
      run: npm run backend-test

    - name: Instrument the frontend code
      run: cp -R public instrumented & npx nyc instrument public instrumented
    
    - name: Run the frontend test cases
      run: rm -rf .nyc_output & npx nyc --nycrc-path .nycrc-frontend cypress run
  
  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}


    - name: Build Docker image
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/task_manager_devops_p05_kiirthanah-docker-img:latest .

    - name: Push Docker image to Docker Hub
      run: docker push thebotwhocriedwolfie/task_manager_devops_p05_kiirthanah-docker-img:latest

  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Log in to Azure
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Set up kubectl to use your AKS cluster
      - name: Set up AKS
        run: |
          az aks get-credentials --resource-group rmsResourceGroup --name rmsAKSCluster --overwrite-existing

      # Deploy to AKS
      - name: Deploy to AKS
        run: |
          kubectl apply -f rms-deployment.yaml
          kubectl apply -f rms-service.yaml
